---
title: "Ping Comparison and Analysis"
author: "Daniel Michelin, Erik Hartig, Nick Swain"
date: "June 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
ping_times <- read.csv("times.csv")
normality <- read.csv("NormalityCheckTimes.csv")
normality2 <- read.csv("NormalityCheckTimes2.csv")
```


```{r cars}
#normality check
hist(normality$TIME,breaks=50)
qqnorm(normality$TIME)
qqline(normality$TIME)
barplot(normality$TIME)

#normality check inside of a "chunk"
hist(normality2$TIME[111:190],breaks=50)
qqnorm(normality2$TIME[111:190])
qqline(normality2$TIME[111:190])
barplot(normality2$TIME[111:190])
boxplot(normality2$TIME[111:190])
summary(normality2$TIME[111:190])

# Summary statistics
summary(ping_times)
hist(ping_times$TIME)
KC = subset(ping_times,select=TIME,LOC=="KC",drop=T)
OK = subset(ping_times,select=TIME,LOC=="OK",drop=T)
hist(KC)
hist(OK)
qqnorm(KC)
qqline(KC)
qqnorm(OK)
qqline(OK)
barplot(KC)
barplot(OK)
var(OK)
var(KC)
mean(OK)
mean(KC)

#Theoretical confidence interval
t.test(KC,OK)

# 95% confidence interval
N <- 10^4
times.diff.mean <- numeric(N)
for(i in 1:N){
  x <- sample(KC, 36, replace=TRUE)
  y <- sample(OK,36, replace=TRUE)
  times.diff.mean[i] <- mean(x) - mean(y)
}
hist(times.diff.mean, main = "Bootstrap distribution of difference in means") 
abline(v = mean(KC) - mean(OK), col = "blue", lty = 2)
dev.new() # Open new graphics device 
qqnorm(times.diff.mean) 
qqline(times.diff.mean)
obs = mean(KC) - mean(OK)
mean(times.diff.mean)
obs
quantile(times.diff.mean,c(0.025,0.975))

# P value
N <- 10^4
result <- numeric(N)
for(i in 1:N){
  index <- sample(72,36,FALSE)
  result[i] <- mean(ping_times$TIME[index]) - mean(ping_times$TIME[-index])
}

# 2 sided test p value
((sum(result < obs)+1)/N)*2


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
GammaNLL <- function(pars, data){
  alpha <- pars[[1]]
  theta <- pars[[2]]
  return (-sum(dgamma(data, shape = alpha, scale = theta, log = TRUE)))
}
Fit <- nloptr(x0 = c(guess1, guess2), eval_f = GammaNLL, lb = c(0,0), data = data,
              opts = list(algorithm = "NLOPT_LN_SBPLX", maxeval = 1e5))
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
